### PR TITLE
rename block files with ci suffix, add msw support to xml cinder block, add vs2013 sample projects

### PR DESCRIPTION
**Pull request by q-depot**

### CODE REVIEW

**Comment by notlion** [comment]
Great! Thanks for doing the initial work on this. I'll test it out on my windows box tonight. First, a couple things:

- Would you mind changing the target of this PR to the `msw` branch?
- Some build files seem to have crept in. Please remove those and move the vc2013 entries in the .gitignore to the sample directories.
- Formatting on the edits to `HelloWorldApp.cpp` should be consistent with the rest of the file. (spaces vs tabs, spaces between operators) Also is there no M_PI_2 in vc2013?

In addition to that, the OS X and iOS projects will need to be updated, but I can take care of that if you want.

Thanks!

**Comment by notlion** [comment]
I went ahead and made these changes in 3bae19f6a3fe215a7a5c1d6ac23affb414a88b12. I'll fix it up on OS X and iOS tomorrow, and then merge into master. The msw branch should be good to go on windows, though. Thanks for the poke :)

**Comment by q-depot** [comment]
thank you, sorry I forgot the ios stuff, great work.

**Comment by notlion** [comment]
I just merged this into master. Let me know if you have any problems with the vs2013 projects.

**Pull request closed without merging**
